openapi: 3.0.0
info:
  title: Product API Documentation
  version: 1.0.0
  description: This is the API documentation for the Farm Stand application.
servers:
- url: http://localhost:3000
  description: Local server
tags:
- name: Products
paths:
  /products:
    get:
      tags:
      - Products
      summary: Fetch a list of products
      description: Retrieve a list of all products from the database.
      responses:
        "200":
          description: A list of products
    post:
      tags:
      - Products
      summary: Create a new product
      description: Add a new product to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Spinach
                price:
                  type: number
                  example: 2.99
                category:
                  type: string
                  example: vegetable
      responses:
        "201":
          description: Product created successfully
  /products/{id}:
    get:
      tags:
      - Products
      summary: Retrieve a product by ID
      description: Retrieve a specific product using its ID.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: The requested product
    patch:
      tags:
      - Products
      summary: Update a product by ID
      description: Update details of a specific product using its ID.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Product Name
                price:
                  type: number
                  example: 3.99
                category:
                  type: string
                  example: vegetable
      responses:
        "200":
          description: Product updated successfully
    delete:
      tags:
      - Products
      summary: Delete a product by ID
      description: Remove a specific product from the database.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Product deleted successfully
